version: '3'
services:
  redis:
    image: redis:6.0
    command: redis-server --requirepass default
    ports:
      - 6379:6379

  mysql:
    network_mode: "bridge"
    environment:
      # root账号的密码
      MYSQL_ROOT_PASSWORD: "root"
      # user的账号密码，这里的账号不能设置为root
      MYSQL_USER: 'admin'
      MYSQL_PASS: 'root'
    image: "mysql:5.7"
    volumes:
      - "./db:/var/lib/mysql"
      - "./conf/my.cnf:/etc/my.cnf"
      - "./init:/docker-entrypoint-initdb.d/"
    ports:
      - "3306:3306"